name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  PROJECT_PATH: 'vscodedotnet/vscodedotnet.csproj'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
